# Site settings
<<<<<<< HEAD
title: HyG
email: gaohaoyang126@126.com
description: 浩阳的博客 前端爱好者
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
=======
name: Less Or More
email: 331852103@qq.com
author: taomw
github: https://331852103.github.io/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。
>>>>>>> 2ef20bd84ac25c0170cd11bd2aa0f6516b5996a5

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Gaohaoyang
permalink: /:year/:month/:day/:title/
<<<<<<< HEAD
=======
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 331852103
highlighter: Rouge
>>>>>>> 2ef20bd84ac25c0170cd11bd2aa0f6516b5996a5

# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
